apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T06:44:54Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1609"
  uid: a2cbdd7a-7f66-4710-b484-aa42dc63834f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.94.39
  clusterIPs:
  - 10.107.94.39
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31180
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
